package plate

// Code generated from https://tool.browser.qq.com/carnumber.html - DO NOT EDIT.
// Captured 2026-08-17. Contains 31 provincial-level divisions.
var provinces = []Province{
	{
		Name:    "北京市",
		Short:   "京",
		EngName: "beijing",
		Codes: []Code{
			{Code: "京A", Districts: []string{"北京市"}},
			{Code: "京B", Districts: []string{"北京市"}},
			{Code: "京C", Districts: []string{"北京市"}},
			{Code: "京D", Districts: []string{"北京市"}},
			{Code: "京E", Districts: []string{"北京市"}},
			{Code: "京H", Districts: []string{"中央国家机关使用"}},
			{Code: "京J", Districts: []string{"中央国家机关使用"}},
			{Code: "京K", Districts: []string{"中央国家机关使用"}},
			{Code: "京L", Districts: []string{"中央国家机关使用"}},
			{Code: "京M", Districts: []string{"中央国家机关使用"}},
			{Code: "京N", Districts: []string{"中央国家机关使用"}},
			{Code: "京O", Districts: []string{"中央国家机关使用"}},
			{Code: "京V", Districts: []string{"中央警卫局使用"}},
			{Code: "京Y", Districts: []string{"北京市"}},
		},
	},
	{
		Name:    "上海市",
		Short:   "沪",
		EngName: "shanghai",
		Codes: []Code{
			{Code: "沪A", Districts: []string{"上海市"}},
			{Code: "沪B", Districts: []string{"上海市"}},
			{Code: "沪C", Districts: []string{"上海市"}},
			{Code: "沪D", Districts: []string{"上海市"}},
			{Code: "沪E", Districts: []string{"上海市"}},
			{Code: "沪F", Districts: []string{"上海市"}},
			{Code: "沪G", Districts: []string{"上海市"}},
			{Code: "沪H", Districts: []string{"上海市"}},
			{Code: "沪J", Districts: []string{"上海市"}},
			{Code: "沪K", Districts: []string{"上海市"}},
			{Code: "沪L", Districts: []string{"上海市"}},
			{Code: "沪M", Districts: []string{"上海市"}},
			{Code: "沪N", Districts: []string{"上海市"}},
			{Code: "沪R", Districts: []string{"崇明区"}},
		},
	},
	{
		Name:    "天津市",
		Short:   "津",
		EngName: "tianjin",
		Codes: []Code{
			{Code: "津A", Districts: []string{"天津市"}},
			{Code: "津B", Districts: []string{"天津市"}},
			{Code: "津C", Districts: []string{"天津市"}},
			{Code: "津D", Districts: []string{"天津市"}},
			{Code: "津E", Districts: []string{"天津市（出租车）"}},
			{Code: "津F", Districts: []string{"天津市"}},
			{Code: "津G", Districts: []string{"天津市"}},
			{Code: "津H", Districts: []string{"天津市"}},
		},
	},
	{
		Name:    "重庆市",
		Short:   "渝",
		EngName: "chongqing",
		Codes: []Code{
			{Code: "渝A", Districts: []string{"重庆市主城区"}},
			{Code: "渝B", Districts: []string{"重庆市主城区"}},
			{Code: "渝C", Districts: []string{"永川区", "江津区", "合川区", "潼南区", "铜梁区", "壁山区", "大足区", "綦江区", "荣昌区"}},
			{Code: "渝D", Districts: []string{"重庆市主城区"}},
			{Code: "渝F", Districts: []string{"万州区", "梁平区", "城口县", "巫山县", "巫溪县", "忠县", "开州区", "奉节县", "云阳县"}},
			{Code: "渝G", Districts: []string{"涪陵区", "南川区", "垫江县", "丰都县", "武隆区"}},
			{Code: "渝H", Districts: []string{"黔江区", "石柱土家族自治县", "秀山土家族苗族自治县", "酉阳土家族苗族自治县", "彭水苗族土家族自治县"}},
		},
	},
	{
		Name:    "安徽省",
		Short:   "皖",
		EngName: "anhui",
		Codes: []Code{
			{Code: "皖A", Districts: []string{"合肥市"}},
			{Code: "皖B", Districts: []string{"芜湖市"}},
			{Code: "皖C", Districts: []string{"蚌埠市"}},
			{Code: "皖D", Districts: []string{"淮南市"}},
			{Code: "皖E", Districts: []string{"马鞍山市"}},
			{Code: "皖F", Districts: []string{"淮北市"}},
			{Code: "皖G", Districts: []string{"铜陵市"}},
			{Code: "皖H", Districts: []string{"安庆市"}},
			{Code: "皖J", Districts: []string{"黄山市"}},
			{Code: "皖K", Districts: []string{"阜阳市"}},
			{Code: "皖L", Districts: []string{"宿州市"}},
			{Code: "皖M", Districts: []string{"滁州市"}},
			{Code: "皖N", Districts: []string{"六安市"}},
			{Code: "皖P", Districts: []string{"宣城市"}},
			{Code: "皖Q", Districts: []string{"巢湖市"}},
			{Code: "皖R", Districts: []string{"池州市"}},
			{Code: "皖S", Districts: []string{"亳州市"}},
		},
	},
	{
		Name:    "河北省",
		Short:   "冀",
		EngName: "hebei",
		Codes: []Code{
			{Code: "冀A", Districts: []string{"石家庄市"}},
			{Code: "冀B", Districts: []string{"唐山市"}},
			{Code: "冀C", Districts: []string{"秦皇岛市"}},
			{Code: "冀D", Districts: []string{"邯郸市"}},
			{Code: "冀E", Districts: []string{"邢台市"}},
			{Code: "冀F", Districts: []string{"保定市"}},
			{Code: "冀G", Districts: []string{"张家口市"}},
			{Code: "冀H", Districts: []string{"承德市"}},
			{Code: "冀J", Districts: []string{"沧州市"}},
			{Code: "冀R", Districts: []string{"廊坊市"}},
			{Code: "冀T", Districts: []string{"衡水市"}},
		},
	},
	{
		Name:    "河南省",
		Short:   "豫",
		EngName: "henan",
		Codes: []Code{
			{Code: "豫A", Districts: []string{"郑州市"}},
			{Code: "豫B", Districts: []string{"开封市"}},
			{Code: "豫C", Districts: []string{"洛阳市"}},
			{Code: "豫D", Districts: []string{"平顶山市"}},
			{Code: "豫E", Districts: []string{"安阳市"}},
			{Code: "豫F", Districts: []string{"鹤壁市"}},
			{Code: "豫G", Districts: []string{"新乡市"}},
			{Code: "豫H", Districts: []string{"焦作市"}},
			{Code: "豫J", Districts: []string{"濮阳市"}},
			{Code: "豫K", Districts: []string{"许昌市"}},
			{Code: "豫L", Districts: []string{"漯河市"}},
			{Code: "豫M", Districts: []string{"三门峡市"}},
			{Code: "豫N", Districts: []string{"商丘市"}},
			{Code: "豫P", Districts: []string{"周口市"}},
			{Code: "豫Q", Districts: []string{"驻马店市"}},
			{Code: "豫R", Districts: []string{"南阳市"}},
			{Code: "豫S", Districts: []string{"信阳市"}},
			{Code: "豫U", Districts: []string{"济源市"}},
		},
	},
	{
		Name:    "山东省",
		Short:   "鲁",
		EngName: "shandong",
		Codes: []Code{
			{Code: "鲁A", Districts: []string{"济南市"}},
			{Code: "鲁B", Districts: []string{"青岛市"}},
			{Code: "鲁C", Districts: []string{"淄博市"}},
			{Code: "鲁D", Districts: []string{"枣庄市"}},
			{Code: "鲁E", Districts: []string{"东营市"}},
			{Code: "鲁F", Districts: []string{"烟台市"}},
			{Code: "鲁G", Districts: []string{"潍坊市"}},
			{Code: "鲁H", Districts: []string{"济宁市"}},
			{Code: "鲁J", Districts: []string{"泰安市"}},
			{Code: "鲁K", Districts: []string{"威海市"}},
			{Code: "鲁L", Districts: []string{"日照市"}},
			{Code: "鲁M", Districts: []string{"滨州市"}},
			{Code: "鲁N", Districts: []string{"德州市"}},
			{Code: "鲁P", Districts: []string{"聊城市"}},
			{Code: "鲁Q", Districts: []string{"临沂市"}},
			{Code: "鲁R", Districts: []string{"菏泽市"}},
			{Code: "鲁S", Districts: []string{"莱芜市"}},
			{Code: "鲁U", Districts: []string{"青岛市增补"}},
			{Code: "鲁V", Districts: []string{"潍坊市增补"}},
		},
	},
	{
		Name:    "山西省",
		Short:   "晋",
		EngName: "shanxi",
		Codes: []Code{
			{Code: "晋A", Districts: []string{"太原市"}},
			{Code: "晋B", Districts: []string{"大同市"}},
			{Code: "晋C", Districts: []string{"阳泉市"}},
			{Code: "晋D", Districts: []string{"长治市"}},
			{Code: "晋E", Districts: []string{"晋城市"}},
			{Code: "晋F", Districts: []string{"朔州市"}},
			{Code: "晋H", Districts: []string{"忻州市"}},
			{Code: "晋J", Districts: []string{"吕梁市"}},
			{Code: "晋K", Districts: []string{"晋中市"}},
			{Code: "晋L", Districts: []string{"临汾市"}},
			{Code: "晋M", Districts: []string{"运城市"}},
		},
	},
	{
		Name:    "黑龙江省",
		Short:   "黑",
		EngName: "heilongjiang",
		Codes: []Code{
			{Code: "黑A", Districts: []string{"哈尔滨市"}},
			{Code: "黑B", Districts: []string{"齐齐哈尔市"}},
			{Code: "黑C", Districts: []string{"牡丹江市"}},
			{Code: "黑D", Districts: []string{"佳木斯市"}},
			{Code: "黑E", Districts: []string{"大庆市"}},
			{Code: "黑F", Districts: []string{"伊春市"}},
			{Code: "黑G", Districts: []string{"鸡西市"}},
			{Code: "黑H", Districts: []string{"鹤岗市"}},
			{Code: "黑J", Districts: []string{"双鸭山市"}},
			{Code: "黑K", Districts: []string{"七台河市"}},
			{Code: "黑L", Districts: []string{"松花江地区（已并入哈尔滨市）"}},
			{Code: "黑M", Districts: []string{"绥化市"}},
			{Code: "黑N", Districts: []string{"黑河市"}},
			{Code: "黑P", Districts: []string{"大兴安岭地区"}},
			{Code: "黑R", Districts: []string{"农垦系统"}},
		},
	},
	{
		Name:    "辽宁省",
		Short:   "辽",
		EngName: "liaoning",
		Codes: []Code{
			{Code: "辽A", Districts: []string{"沈阳市"}},
			{Code: "辽B", Districts: []string{"大连市"}},
			{Code: "辽C", Districts: []string{"鞍山市"}},
			{Code: "辽D", Districts: []string{"抚顺市"}},
			{Code: "辽E", Districts: []string{"本溪市"}},
			{Code: "辽F", Districts: []string{"丹东市"}},
			{Code: "辽G", Districts: []string{"锦州市"}},
			{Code: "辽H", Districts: []string{"营口市"}},
			{Code: "辽J", Districts: []string{"阜新市"}},
			{Code: "辽K", Districts: []string{"辽阳市"}},
			{Code: "辽L", Districts: []string{"盘锦市"}},
			{Code: "辽M", Districts: []string{"铁岭市"}},
			{Code: "辽N", Districts: []string{"朝阳市"}},
			{Code: "辽P", Districts: []string{"葫芦岛市"}},
			{Code: "辽V", Districts: []string{"省直机关"}},
		},
	},
	{
		Name:    "吉林省",
		Short:   "吉",
		EngName: "jilin",
		Codes: []Code{
			{Code: "吉A", Districts: []string{"长春市"}},
			{Code: "吉B", Districts: []string{"吉林市"}},
			{Code: "吉C", Districts: []string{"四平市"}},
			{Code: "吉D", Districts: []string{"辽源市"}},
			{Code: "吉E", Districts: []string{"通化市"}},
			{Code: "吉F", Districts: []string{"白山市"}},
			{Code: "吉G", Districts: []string{"白城市"}},
			{Code: "吉H", Districts: []string{"延边朝鲜族自治州"}},
			{Code: "吉J", Districts: []string{"松原市"}},
		},
	},
	{
		Name:    "内蒙古自治区",
		Short:   "蒙",
		EngName: "neimenggu",
		Codes: []Code{
			{Code: "蒙A", Districts: []string{"呼和浩特市"}},
			{Code: "蒙B", Districts: []string{"包头市"}},
			{Code: "蒙C", Districts: []string{"乌海市"}},
			{Code: "蒙D", Districts: []string{"赤峰市"}},
			{Code: "蒙E", Districts: []string{"呼伦贝尔市"}},
			{Code: "蒙F", Districts: []string{"兴安盟"}},
			{Code: "蒙G", Districts: []string{"通辽市"}},
			{Code: "蒙H", Districts: []string{"锡林郭勒盟"}},
			{Code: "蒙J", Districts: []string{"乌兰察布盟"}},
			{Code: "蒙K", Districts: []string{"鄂尔多斯市"}},
			{Code: "蒙L", Districts: []string{"巴彦淖尔盟"}},
			{Code: "蒙M", Districts: []string{"阿拉善盟"}},
		},
	},
	{
		Name:    "湖北省",
		Short:   "鄂",
		EngName: "hubei",
		Codes: []Code{
			{Code: "鄂A", Districts: []string{"武汉市"}},
			{Code: "鄂B", Districts: []string{"黄石市"}},
			{Code: "鄂C", Districts: []string{"十堰市"}},
			{Code: "鄂D", Districts: []string{"荆州市"}},
			{Code: "鄂E", Districts: []string{"宜昌市"}},
			{Code: "鄂F", Districts: []string{"襄樊市"}},
			{Code: "鄂G", Districts: []string{"鄂州市"}},
			{Code: "鄂H", Districts: []string{"荆门市"}},
			{Code: "鄂J", Districts: []string{"黄冈市"}},
			{Code: "鄂K", Districts: []string{"孝感市"}},
			{Code: "鄂L", Districts: []string{"咸宁市"}},
			{Code: "鄂M", Districts: []string{"仙桃市"}},
			{Code: "鄂N", Districts: []string{"潜江市"}},
			{Code: "鄂P", Districts: []string{"神农架林区"}},
			{Code: "鄂Q", Districts: []string{"恩施土家族苗族自治州"}},
			{Code: "鄂R", Districts: []string{"天门市"}},
			{Code: "鄂S", Districts: []string{"随州市"}},
		},
	},
	{
		Name:    "湖南省",
		Short:   "湘",
		EngName: "hunan",
		Codes: []Code{
			{Code: "湘A", Districts: []string{"长沙市"}},
			{Code: "湘B", Districts: []string{"株洲市"}},
			{Code: "湘C", Districts: []string{"湘潭市"}},
			{Code: "湘D", Districts: []string{"衡阳市"}},
			{Code: "湘E", Districts: []string{"邵阳市"}},
			{Code: "湘F", Districts: []string{"岳阳市"}},
			{Code: "湘G", Districts: []string{"张家界市"}},
			{Code: "湘H", Districts: []string{"益阳市"}},
			{Code: "湘J", Districts: []string{"常德市"}},
			{Code: "湘K", Districts: []string{"娄底市"}},
			{Code: "湘L", Districts: []string{"郴州市"}},
			{Code: "湘M", Districts: []string{"永州市"}},
			{Code: "湘N", Districts: []string{"怀化市"}},
			{Code: "湘U", Districts: []string{"湘西土家族苗族自治州"}},
		},
	},
	{
		Name:    "江苏省",
		Short:   "苏",
		EngName: "jiangsu",
		Codes: []Code{
			{Code: "苏A", Districts: []string{"南京市"}},
			{Code: "苏B", Districts: []string{"无锡市"}},
			{Code: "苏C", Districts: []string{"徐州市"}},
			{Code: "苏D", Districts: []string{"常州市"}},
			{Code: "苏E", Districts: []string{"苏州市"}},
			{Code: "苏F", Districts: []string{"南通市"}},
			{Code: "苏G", Districts: []string{"连云港市"}},
			{Code: "苏H", Districts: []string{"淮安市"}},
			{Code: "苏J", Districts: []string{"盐城市"}},
			{Code: "苏K", Districts: []string{"扬州市"}},
			{Code: "苏L", Districts: []string{"镇江市"}},
			{Code: "苏M", Districts: []string{"泰州市"}},
			{Code: "苏N", Districts: []string{"宿迁市"}},
		},
	},
	{
		Name:    "江西省",
		Short:   "赣",
		EngName: "jiangxi",
		Codes: []Code{
			{Code: "赣A", Districts: []string{"南昌市"}},
			{Code: "赣B", Districts: []string{"赣州市"}},
			{Code: "赣C", Districts: []string{"宜春市"}},
			{Code: "赣D", Districts: []string{"吉安市"}},
			{Code: "赣E", Districts: []string{"上饶市"}},
			{Code: "赣F", Districts: []string{"抚州市"}},
			{Code: "赣G", Districts: []string{"九江市"}},
			{Code: "赣H", Districts: []string{"景德镇市"}},
			{Code: "赣J", Districts: []string{"萍乡市"}},
			{Code: "赣K", Districts: []string{"新余市"}},
			{Code: "赣L", Districts: []string{"鹰潭市"}},
			{Code: "赣M", Districts: []string{"省直系统"}},
		},
	},
	{
		Name:    "浙江省",
		Short:   "浙",
		EngName: "zhejiang",
		Codes: []Code{
			{Code: "浙A", Districts: []string{"杭州市"}},
			{Code: "浙B", Districts: []string{"宁波市"}},
			{Code: "浙C", Districts: []string{"温州市"}},
			{Code: "浙D", Districts: []string{"绍兴市"}},
			{Code: "浙E", Districts: []string{"湖州市"}},
			{Code: "浙F", Districts: []string{"嘉兴市"}},
			{Code: "浙G", Districts: []string{"金华市"}},
			{Code: "浙H", Districts: []string{"衢州市"}},
			{Code: "浙J", Districts: []string{"台州市"}},
			{Code: "浙K", Districts: []string{"丽水市"}},
			{Code: "浙L", Districts: []string{"舟山市"}},
		},
	},
	{
		Name:    "福建省",
		Short:   "闽",
		EngName: "fujian",
		Codes: []Code{
			{Code: "闽A", Districts: []string{"福州市"}},
			{Code: "闽B", Districts: []string{"莆田市"}},
			{Code: "闽C", Districts: []string{"泉州市"}},
			{Code: "闽D", Districts: []string{"厦门市"}},
			{Code: "闽E", Districts: []string{"漳州市"}},
			{Code: "闽F", Districts: []string{"龙岩市"}},
			{Code: "闽G", Districts: []string{"三明市"}},
			{Code: "闽H", Districts: []string{"南平市"}},
			{Code: "闽J", Districts: []string{"宁德市"}},
			{Code: "闽K", Districts: []string{"省直系统，平潭"}},
		},
	},
	{
		Name:    "广东省",
		Short:   "粤",
		EngName: "guangdong",
		Codes: []Code{
			{Code: "粤A", Districts: []string{"广州市"}},
			{Code: "粤B", Districts: []string{"深圳市"}},
			{Code: "粤C", Districts: []string{"珠海市"}},
			{Code: "粤D", Districts: []string{"汕头市"}},
			{Code: "粤E", Districts: []string{"佛山市"}},
			{Code: "粤F", Districts: []string{"韶关市"}},
			{Code: "粤G", Districts: []string{"湛江市"}},
			{Code: "粤H", Districts: []string{"肇庆市"}},
			{Code: "粤J", Districts: []string{"江门市"}},
			{Code: "粤K", Districts: []string{"茂名市"}},
			{Code: "粤L", Districts: []string{"惠州市"}},
			{Code: "粤M", Districts: []string{"梅州市"}},
			{Code: "粤N", Districts: []string{"汕尾市"}},
			{Code: "粤P", Districts: []string{"河源市"}},
			{Code: "粤Q", Districts: []string{"阳江市"}},
			{Code: "粤R", Districts: []string{"清远市"}},
			{Code: "粤S", Districts: []string{"东莞市"}},
			{Code: "粤T", Districts: []string{"中山市"}},
			{Code: "粤U", Districts: []string{"潮州市"}},
			{Code: "粤V", Districts: []string{"揭阳市"}},
			{Code: "粤W", Districts: []string{"云浮市"}},
			{Code: "粤X", Districts: []string{"顺德区"}},
			{Code: "粤Y", Districts: []string{"南海区"}},
			{Code: "粤Z", Districts: []string{"香港澳门进入内地车辆"}},
		},
	},
	{
		Name:    "广西壮族自治区",
		Short:   "桂",
		EngName: "guangxi",
		Codes: []Code{
			{Code: "桂A", Districts: []string{"南宁市"}},
			{Code: "桂B", Districts: []string{"柳州市"}},
			{Code: "桂C", Districts: []string{"桂林市"}},
			{Code: "桂D", Districts: []string{"梧州市"}},
			{Code: "桂E", Districts: []string{"北海市"}},
			{Code: "桂F", Districts: []string{"南宁地区"}},
			{Code: "桂G", Districts: []string{"柳州地区"}},
			{Code: "桂H", Districts: []string{"桂林地区（已并入桂林市）"}},
			{Code: "桂J", Districts: []string{"贺州市"}},
			{Code: "桂K", Districts: []string{"玉林市"}},
			{Code: "桂L", Districts: []string{"百色市"}},
			{Code: "桂M", Districts: []string{"河池市"}},
			{Code: "桂N", Districts: []string{"钦州市"}},
			{Code: "桂P", Districts: []string{"防城港市"}},
			{Code: "桂R", Districts: []string{"贵港市"}},
		},
	},
	{
		Name:    "海南省",
		Short:   "琼",
		EngName: "hainan",
		Codes: []Code{
			{Code: "琼A", Districts: []string{"海口市"}},
			{Code: "琼B", Districts: []string{"三亚市"}},
			{Code: "琼C", Districts: []string{"三沙市", "琼海市", "万宁市", "文昌市", "澄迈县", "屯昌县", "定安县", "临高县"}},
			{Code: "琼D", Districts: []string{"五指山市", "东方市", "白沙黎族自治县", "昌江黎族自治县", "陵水黎族自治县", "乐东黎族自治县", "保亭黎族苗族自治县", "琼中黎族苗族自治县"}},
			{Code: "琼E", Districts: []string{"洋浦开发区"}},
			{Code: "琼F", Districts: []string{"儋州市"}},
		},
	},
	{
		Name:    "四川省",
		Short:   "川",
		EngName: "sichuan",
		Codes: []Code{
			{Code: "川A", Districts: []string{"成都市"}},
			{Code: "川G", Districts: []string{"成都市"}},
			{Code: "川B", Districts: []string{"绵阳市"}},
			{Code: "川C", Districts: []string{"自贡市"}},
			{Code: "川D", Districts: []string{"攀枝花市"}},
			{Code: "川E", Districts: []string{"泸州市"}},
			{Code: "川F", Districts: []string{"德阳市"}},
			{Code: "川H", Districts: []string{"广元市"}},
			{Code: "川J", Districts: []string{"遂宁市"}},
			{Code: "川K", Districts: []string{"内江市"}},
			{Code: "川L", Districts: []string{"乐山市"}},
			{Code: "川M", Districts: []string{"资阳市"}},
			{Code: "川Q", Districts: []string{"宜宾市"}},
			{Code: "川R", Districts: []string{"南充市"}},
			{Code: "川S", Districts: []string{"达州市"}},
			{Code: "川T", Districts: []string{"雅安市"}},
			{Code: "川U", Districts: []string{"阿坝藏族羌族自治州"}},
			{Code: "川V", Districts: []string{"甘孜藏族自治州"}},
			{Code: "川W", Districts: []string{"凉山彝族自治州"}},
			{Code: "川X", Districts: []string{"广安市"}},
			{Code: "川Y", Districts: []string{"巴中市"}},
			{Code: "川Z", Districts: []string{"眉山市"}},
		},
	},
	{
		Name:    "陕西省",
		Short:   "陕",
		EngName: "shanxi",
		Codes: []Code{
			{Code: "陕A", Districts: []string{"西安市"}},
			{Code: "陕B", Districts: []string{"铜川市"}},
			{Code: "陕C", Districts: []string{"宝鸡市"}},
			{Code: "陕D", Districts: []string{"咸阳市"}},
			{Code: "陕E", Districts: []string{"渭南市"}},
			{Code: "陕F", Districts: []string{"汉中市"}},
			{Code: "陕G", Districts: []string{"安康市"}},
			{Code: "陕H", Districts: []string{"商洛市"}},
			{Code: "陕J", Districts: []string{"延安市"}},
			{Code: "陕K", Districts: []string{"榆林市"}},
			{Code: "陕U", Districts: []string{"省直系统(已取消)"}},
			{Code: "陕V", Districts: []string{"杨凌高新农业示范区"}},
		},
	},
	{
		Name:    "云南省",
		Short:   "云",
		EngName: "yunnan",
		Codes: []Code{
			{Code: "云A", Districts: []string{"昆明市"}},
			{Code: "云C", Districts: []string{"昭通市"}},
			{Code: "云D", Districts: []string{"曲靖市"}},
			{Code: "云E", Districts: []string{"楚雄彝族自治州"}},
			{Code: "云F", Districts: []string{"玉溪市"}},
			{Code: "云G", Districts: []string{"红河哈尼族彝族自治州"}},
			{Code: "云H", Districts: []string{"文山壮族苗族自治州"}},
			{Code: "云J", Districts: []string{"普洱市"}},
			{Code: "云K", Districts: []string{"西双版纳傣族自治州"}},
			{Code: "云L", Districts: []string{"大理白族自治州"}},
			{Code: "云M", Districts: []string{"保山市"}},
			{Code: "云N", Districts: []string{"德宏傣族景颇族自治州"}},
			{Code: "云P", Districts: []string{"丽江市"}},
			{Code: "云Q", Districts: []string{"怒江傈僳族自治州"}},
			{Code: "云R", Districts: []string{"迪庆藏族自治州"}},
			{Code: "云S", Districts: []string{"临沧地区"}},
		},
	},
	{
		Name:    "贵州省",
		Short:   "贵",
		EngName: "guizhou",
		Codes: []Code{
			{Code: "贵A", Districts: []string{"贵阳市"}},
			{Code: "贵B", Districts: []string{"六盘水市"}},
			{Code: "贵C", Districts: []string{"遵义市"}},
			{Code: "贵D", Districts: []string{"铜仁地区"}},
			{Code: "贵E", Districts: []string{"黔西南布依族苗族自治州"}},
			{Code: "贵F", Districts: []string{"毕节地区"}},
			{Code: "贵G", Districts: []string{"安顺市"}},
			{Code: "贵H", Districts: []string{"黔东南苗族侗族自治州"}},
			{Code: "贵J", Districts: []string{"黔南布依族苗族自治州"}},
		},
	},
	{
		Name:    "甘肃省",
		Short:   "甘",
		EngName: "gansu",
		Codes: []Code{
			{Code: "甘A", Districts: []string{"兰州市"}},
			{Code: "甘B", Districts: []string{"嘉峪关市"}},
			{Code: "甘C", Districts: []string{"金昌市"}},
			{Code: "甘D", Districts: []string{"白银市"}},
			{Code: "甘E", Districts: []string{"天水市"}},
			{Code: "甘F", Districts: []string{"酒泉市"}},
			{Code: "甘G", Districts: []string{"张掖市"}},
			{Code: "甘H", Districts: []string{"武威市"}},
			{Code: "甘J", Districts: []string{"定西地区"}},
			{Code: "甘K", Districts: []string{"陇南地区"}},
			{Code: "甘L", Districts: []string{"平凉市"}},
			{Code: "甘M", Districts: []string{"庆阳市"}},
			{Code: "甘N", Districts: []string{"临夏回族自治州"}},
			{Code: "甘P", Districts: []string{"甘南藏族自治州"}},
		},
	},
	{
		Name:    "青海省",
		Short:   "青",
		EngName: "qinghai",
		Codes: []Code{
			{Code: "青A", Districts: []string{"西宁市"}},
			{Code: "青B", Districts: []string{"海东地区"}},
			{Code: "青C", Districts: []string{"海北藏族自治州"}},
			{Code: "青D", Districts: []string{"黄南藏族自治州"}},
			{Code: "青E", Districts: []string{"海南藏族自治州"}},
			{Code: "青F", Districts: []string{"果洛藏族自治州"}},
			{Code: "青G", Districts: []string{"玉树藏族自治州"}},
			{Code: "青H", Districts: []string{"海西蒙古族藏族自治州"}},
		},
	},
	{
		Name:    "宁夏回族自治区",
		Short:   "宁",
		EngName: "ningxia",
		Codes: []Code{
			{Code: "宁A", Districts: []string{"银川市"}},
			{Code: "宁B", Districts: []string{"石嘴山市"}},
			{Code: "宁C", Districts: []string{"吴忠市"}},
			{Code: "宁D", Districts: []string{"固原市"}},
			{Code: "宁E", Districts: []string{"中卫市"}},
		},
	},
	{
		Name:    "西藏自治区",
		Short:   "藏",
		EngName: "xizang",
		Codes: []Code{
			{Code: "藏A", Districts: []string{"拉萨市"}},
			{Code: "藏B", Districts: []string{"昌都地区"}},
			{Code: "藏C", Districts: []string{"山南地区"}},
			{Code: "藏D", Districts: []string{"日喀则地区"}},
			{Code: "藏E", Districts: []string{"那曲地区"}},
			{Code: "藏F", Districts: []string{"阿里地区"}},
			{Code: "藏G", Districts: []string{"林芝地区"}},
			{Code: "藏H", Districts: []string{"驻四川省天全县车辆管理所"}},
			{Code: "藏J", Districts: []string{"驻青海省格尔木市车辆管理所"}},
		},
	},
	{
		Name:    "新疆维吾尔自治区",
		Short:   "新",
		EngName: "xinjiang",
		Codes: []Code{
			{Code: "新A", Districts: []string{"乌鲁木齐市"}},
			{Code: "新B", Districts: []string{"昌吉回族自治州"}},
			{Code: "新C", Districts: []string{"石河子市"}},
			{Code: "新D", Districts: []string{"奎屯市"}},
			{Code: "新E", Districts: []string{"博尔塔拉蒙古自治州"}},
			{Code: "新F", Districts: []string{"伊犁哈萨克自治州"}},
			{Code: "新G", Districts: []string{"塔城地区"}},
			{Code: "新H", Districts: []string{"阿勒泰地区"}},
			{Code: "新J", Districts: []string{"克拉玛依市"}},
			{Code: "新K", Districts: []string{"吐鲁番地区"}},
			{Code: "新L", Districts: []string{"哈密地区"}},
			{Code: "新M", Districts: []string{"巴音郭楞蒙古自治州"}},
			{Code: "新N", Districts: []string{"阿克苏地区"}},
			{Code: "新P", Districts: []string{"克孜勒苏柯尔克孜自治州"}},
			{Code: "新Q", Districts: []string{"喀什地区"}},
			{Code: "新R", Districts: []string{"和田地区"}},
		},
	},
}
